### ISSUE TITLE
Date sorting/Download issue

### ISSUE THREAD

**Issue by Yobleed** [coinyon/hexcal#1]
It would be nice to have all days sorted instead of randomized.

Also I can't download the calender file for some reason ;)

**Comment by coinyon** [comment]
Good point, I thought they were sorted, but maybe it was just the case with my stakes.

I will take a look at it.

Is there a error message for the download? What browser are you using?

**Comment by Yobleed** [comment]
There is no error message, It's like it's refreshing the page. That's what it looks like. I'm using Chrome.

**Comment by coinyon** [comment]
Please refresh, both issues should be resolved now. Please re-open if you have more problems. Thanks for reporting.
